name: Publish Helm Chart to Artifact Registry

on:
  push:
    branches:
      - master  # Change to your main branch name

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Auth GCP 
          id: 'auth'
          uses: google-github-actions/auth@v0.4.0
          with:
            credentials_json: "${{ secrets.GOOGLE_CREDENTIALS}}"        
        - name: Install and configure Helm
          run: |
            curl -LO "https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz"
            tar -zxvf helm-v3.7.1-linux-amd64.tar.gz
            sudo mv linux-amd64/helm /usr/local/bin/helm
            helm version   
        - name: Set variables
          run: |
            VER=$(cat hello-chart/Chart.yaml | grep "version:"| awk '{print $2}')
            echo "VERSION=$VER" >> $GITHUB_ENV    
        - name: Package Helm Chart
          run: |
            helm package hello-chart .
            helm repo index .
            git config --global user.name mohamed.morshed
            git config --global user.email mohamed.morshed@modeso.ch
            git add .
            git commit -m "push"
            git push 
            

        # - name: Publish Helm Chart to Artifact Registry
        #   run: |
        #      export HELM_EXPERIMENTAL_OCI=1
        #      gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev
        #      gcloud auth configure-docker us-central1-docker.pkg.dev
        #      helm push --debug hello-chart-$VERSION.tgz oci://us-central1-docker.pkg.dev/devops-training-330915/helm-base 
        #     # gcloud artifacts repositories create your-repo-name --location=us-central1
            

