name: Publish Helm Chart to Artifact Registry

on:
  push:
    branches:
      - master  # Change to your main branch name

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2
    #   - name: Auth GCP 
    #     id: 'auth'
    #     uses: google-github-actions/auth@v0.4.0
    #     with:
    #       credentials_json: "${{ secrets.GOOGLE_CREDENTIALS  }}"
      - name: Package Helm Chart
        secrets: inherit
        run: |
          cat ${{ secrets.test }}
          cat "${{ secrets.test }}"

      - name: Install and configure Helm
        run: |
          curl -LO "https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz"
          tar -zxvf helm-v3.7.1-linux-amd64.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm
          helm version   
      - name: Package Helm Chart
        run: |
          helm package hello-chart
        #   gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev

      - name: Publish Helm Chart to Artifact Registry
        run: |
          helm push hello-chart-0.1.0.tgz oci://us-central1-docker.pkg.dev/devops-training-330915/helm-base --version 0.1.0 --username _json_key --password="${{ secrets.GCP_SA_KEY }}
          gcloud artifacts repositories create your-repo-name --location=us-central1
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
    #   - name: Cleanup
    #     run: |
    #       rm $HOME/.docker/config.json

